# Используем Python 3.11 slim
FROM python:3.11-slim

# Системные зависимости для сборки aiohttp
RUN apt-get update && apt-get install -y build-essential

WORKDIR /app

# Копируем и ставим зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код бота
COPY main.py .

# Команда запуска
CMD ["python", "main.py"]